### ISSUE TITLE
Redundant Object

### ISSUE THREAD

**Issue by ariG23498** [RoyARG02/javaNoob#1]
https://github.com/RoyARG02/javaNoob/blob/def8744c318af4b85efa9e411ab270ee4a561e7e/OOPS_lab/Day_3/areaOfShapes2.java#L12

In this line of code, a new object is made, with no use of it. This can be omitted.

**Comment by royarg02** [comment]
Have to initialize the object reference else the compiler gives a __Variable might not have been initialized__ error.
This could be fixed if the statement `user.show( )` is written in each of the `cases` in the `switch` block, but instead I let the garbage collector do it's work.
